# Generated by Django 4.1.3 on 2023-01-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='data_ordered',
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Pepsicola', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/user.jpg', upload_to='static/profile/images'),
        ),
    ]
