# Generated by Django 4.1.3 on 2022-12-31 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_price_service_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='data_ordered',
        ),
    ]
