# Generated by Django 4.1.3 on 2023-01-07 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_service_prices_service_service_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_price',
            new_name='price',
        ),
    ]
