# Generated by Django 4.1.3 on 2023-01-07 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_order_data_ordered_alter_profile_city_and_more'),
        ('dashboard', '0007_rename_service_price_service_price'),
    ]

    operations = [
    ]
